### ISSUE TITLE
Package will not build with Electron Builder

### ISSUE THREAD

**Issue by Chrisbright10** [wouterverweirder/kinect-azure#47]
I have just migrated over to this package from the kinect2 package and am having trouble building the package for production. I keep getting errors that it can't find dependencies and it is looking for the package.json to help resolve it. I wasn't getting this error with the kinect2 package before and I suspect it has to do something with all of the extra needed files for the new kinect-azure package. 

I am also getting lots of issues because of the use of require.js, since I am using a modern frontend framework to load in the camera package I am having to change the require() to window.require, which doesn't seem all that sustainable. Is there a better way to lad in the deps?

**Comment by wouterverweirder** [comment]
Hi Chris,

I've put together a basic demo application with electron-builder, electron-webpack and kinect-azure (with Body Tracking): https://github.com/wouterverweirder/electron-builder-kinect-azure-demo

An important addition to the package.json config, is copying the necessary DLL files for body tracking to work in the release build:

```json
  "build": {
    "appId": "be.aboutme.kinect-azure.electron-builder-kinect-azure-demo",
    "win": {
      "extraFiles": [
        {
          "from": "C:\\Program Files\\Azure Kinect Body Tracking SDK\\tools",
          "to": "./"
        }
      ]
    }
  },
```

**Comment by Chrisbright10** [comment]
I attempted to pull down the project, it isn't working for me, here is the error when i try and build dev

![image](https://user-images.githubusercontent.com/2694666/124832182-80163100-df39-11eb-865b-6f19ef9d706b.png)

**Comment by wouterverweirder** [comment]
You'll get this error when windows can't find the necessary dll files, even when the kinectAzure.node file is there.

I have added an extra script to the package.json file of [the demo project](https://github.com/wouterverweirder/electron-builder-kinect-azure-demo).

Get the latest version, and run

```
npm run copy-dlls
```

before launching in dev mode. I'm assuming the dll files are in the default install directory of the body tracking sdk, aka `C:\Program Files\Azure Kinect Body Tracking SDK\tools`

A distribution build should have worked, as the dll copying is included in the electron-builder config.

**Comment by Chrisbright10** [comment]
I ran it and wasn't able to get it to run, ended up having the same issue even though the dlls successfully copied over

![image](https://user-images.githubusercontent.com/2694666/125341942-71e95b80-e311-11eb-8387-c32782f66f66.png)

![image](https://user-images.githubusercontent.com/2694666/125342006-862d5880-e311-11eb-98a8-13047e7bcb70.png)

**Comment by Chrisbright10** [comment]
I tried downgrading the kinect-azure package to 0.0.19 and that did seem to run, but wasn't able to build a release package.

**Comment by wouterverweirder** [comment]
Ok, I've just pushed some changes on how the prebuild binaries of this module are handled. Try using version 0.2.2 of this library? If not, could you post the full log of what happens when you npm install this module?

**Comment by Chrisbright10** [comment]
One quick fix... the xcopy command wasn't working for me, I looked into it and fixed it... here is the corrected command so that others wont have the same issue I did with that part. I am currently working on the rest, I will update you when I have tried upgrading.

"xcopy \"C:\\Program Files\\Azure Kinect Body Tracking SDK\\tools\" \".\" /H /C /Y"

**Comment by Chrisbright10** [comment]
I still can't get it to build with the new format. below is the yarn install

![image](https://user-images.githubusercontent.com/2694666/125829640-2681dd1c-8a10-4994-8cb7-68afe15983b0.png)

next is the copy-dlls

![image](https://user-images.githubusercontent.com/2694666/125829748-f4a4bb65-4278-4284-9af4-0d652dd7db87.png)

and the rest of the yarn dev

![image](https://user-images.githubusercontent.com/2694666/125829918-0147300c-25df-4959-b7e6-bcce571a6edf.png)

**Comment by Chrisbright10** [comment]
Do you think it might have anything to do with this part of the error message? I have never seen that before....

![image](https://user-images.githubusercontent.com/2694666/125832536-1384d9cf-e647-460a-84c8-2c9343f8cb23.png)

**Comment by wouterverweirder** [comment]
I am assuming the kinectAzure.node file is on your system? Could you open that file with dependency walker (https://www.dependencywalker.com) and check what dll files it is reporting missing?
